services:
type: web
name: booking_ticket
runtime: python
buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
startCommand: "gunicorn booking_ticket.wsgi:application"